name: DotNet CI

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: ["master"]
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.x

      - name: Restore dependencies
        run: dotnet restore Z.QRCodeEncoder.Net

      - name: Build
        run: dotnet build --no-restore Z.QRCodeEncoder.Net
